### ISSUE TITLE
fhsinchy/hello-kube not working on Raspberry Pi 

### ISSUE THREAD

**Issue by raed667** [fhsinchy/kubernetes-handbook-projects#2]
When trying to run the image on a Raspberry Pi 4 I get the error: 

```
$ k get pod
hello-kube                         0/1     CrashLoopBackOff   1          16s

$ k logs hello-kube
standard_init_linux.go:219: exec user process caused: exec format error
```

It looks like the [docker image](
https://hub.docker.com/r/fhsinchy/hello-kube/tags?page=1&ordering=last_updated) is only available for `linux/amd64` architecture. 

Can you please provide an ARM build? Should be pretty straight forward with [buildx](https://docs.docker.com/buildx/working-with-buildx/)

```
$ docker buildx build --platform linux/arm/v7 -t fhsinchy/hello-kube --push
```

Thanks !

**Comment by fhsinchy** [comment]
I can do that, sure, but It'll have to wait until the weekend.

**Comment by raed667** [comment]
Thanks! I [published a version](https://hub.docker.com/repository/docker/raed667/hello-kube/tags?page=1&ordering=last_updated) for running the project on my own pi, but thought it may be helpful for other people if they didn't have to do the same and change the image name in every file.

**Comment by fhsinchy** [comment]
It'll be very helpful. I'll build the images ASAP. Thanks a lot for the valuable contribution.

**Comment by fhsinchy** [comment]
Also, @RaedsLab if you share your builds with me, I'll include them in the handbook for people using a Pi. Sounds good?

**Comment by raed667** [comment]
All the 3 builds are public: 

- https://hub.docker.com/repository/docker/raed667/hello-kube
- https://hub.docker.com/repository/docker/raed667/notes-api
- https://hub.docker.com/repository/docker/raed667/notes-postgres

If there is something more specific I can help you with let me know.

**Comment by fhsinchy** [comment]
@RaedsLab I've updated the handbook with your links. Thanks a lot for your contributions.
